library(drake)
library(plyr)
library(tidyverse)
library(patchwork)
library(rgeos)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rerddap)
library(bayesplot)
library(grid)
library(gridExtra)
library(png)
library(brms)
library(LoLinR) # remotes::install_github("colin-olito/LoLinR")
rstan::rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
